language: generic
sudo: required
sevices:
  - docker

before_install:
  - docker build -t yomarguti/react-test -f ./client/Dockerfile.dev ./client
scripts:
  - docker run -e CI=true yomarguti/react-test npm test

after_success:
  - docker build -t yomarguti/multi-client ./client
  - docker build -t yomarguti/multi-nginx ./nginx
  - docker build -t yomarguti/multi-server ./server
  - docker build -t yomarguti/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push yomarguti/multi-client
  - docker push yomarguti/multi-nginx
  - docker push yomarguti/multi-server
  - docker push yomarguti/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-636262017077
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
